ICTS.Dashboard/Controllers/ICTWFController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ICTS.Data;
using ICTS.Bussiness.UserProfileManage;
using ICTS.Dashboard.Models;

namespace ICTS.Dashboard.Controllers
{
    public class ICTWFController : Controller
    {
        private ICTSDashboardData dbContext = new ICTSDashboardData();

        // GET: /ICTWF/
        public ActionResult Index()
        {

            return View(dbContext.UserProfiles.ToList());

        }

        // GET: /ICTWF/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userprofile = dbContext.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        // GET: /ICTWF/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /ICTWF/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,FrirstName,LastName,MidName,LoginName,Password,Email,Telephone,Status,DateCreate,DateUpdate")] UserProfile userprofile)
        {
            if (ModelState.IsValid)
            {
                userprofile.Id = Guid.NewGuid();
                dbContext.UserProfiles.Add(userprofile);
                dbContext.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userprofile);
        }

        // GET: /ICTWF/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userprofile = dbContext.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        // POST: /ICTWF/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,FrirstName,LastName,MidName,LoginName,Password,Email,Telephone,Status,DateCreate,DateUpdate")] UserProfile userprofile)
        {
            if (ModelState.IsValid)
            {
                dbContext.Entry(userprofile).State = EntityState.Modified;
                dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userprofile);
        }

        // GET: /ICTWF/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userprofile = dbContext.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        // POST: /ICTWF/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            UserProfile userprofile = dbContext.UserProfiles.Find(id);
            dbContext.UserProfiles.Remove(userprofile);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                dbContext.Dispose();
            }
            base.Dispose(disposing);
        }


        // GET: /ICTWF/
        public ActionResult CreateUserWF()
        { 
            return View(); 
        }

        // POST: /ICTWF/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateUserWF([Bind(Include = "Id,FrirstName,LastName,MidName,LoginName,Password,Email,Telephone,Status,DateCreate,DateUpdate")] UserProfile userprofile)
        {
            if (ModelState.IsValid)
            {
                userprofile.Id = Guid.NewGuid();

                IUserProfileManage userManage = new UserProfileManage();
                WFProject project =  userManage.CreateUserProfileWF(userprofile);

                return RedirectToAction("ManagerWF", new { 
                    id = userprofile.Id,
                    projectid = project.Id,
                    instanceId = project.InstanceId
                });
            } 
            return View(userprofile);
        }

        // GET: /ICTWF/Details/5
        public ActionResult ManagerWF(Guid? id, Guid? projectid, Guid? instanceId)
        {
            UserProfileWFModel model = new UserProfileWFModel();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userprofile = dbContext.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            model.userProfile = userprofile;

            IList<WFTask> tasks = dbContext.WFTasks.Where(t => t.WFProjectId == projectid).ToList<WFTask>();

            model.taskWF = tasks;

            return View(model);
        }

        // GET: /ICTWF/Details/5
        public ActionResult ValidateTask(Guid? id, Guid? taskid)
        {
            UserProfileWFModel model = new UserProfileWFModel();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userprofile = dbContext.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            model.userProfile = userprofile;

            WFTask task = dbContext.WFTasks.Find(taskid);

            model.wfTask = task;

            return View(task.TaskName, model);
        }

    }
}

ICTS.Dashboard/Views/ICTWF/Create.cshtml
@model ICTS.Data.UserProfile

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserProfile</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
        <div class="form-group">
            @Html.LabelFor(model => model.FrirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FrirstName)
                @Html.ValidationMessageFor(model => model.FrirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName)
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MidName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MidName)
                @Html.ValidationMessageFor(model => model.MidName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LoginName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LoginName)
                @Html.ValidationMessageFor(model => model.LoginName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telephone, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telephone)
                @Html.ValidationMessageFor(model => model.Telephone)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status)
                @Html.ValidationMessageFor(model => model.Status)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreate)
                @Html.ValidationMessageFor(model => model.DateCreate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateUpdate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateUpdate)
                @Html.ValidationMessageFor(model => model.DateUpdate)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ICTS.Dashboard/Views/ICTWF/CreateUserWF.cshtml
@model ICTS.Data.UserProfile
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br /> 

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
    Create User Profile
</button>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialogWF">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">New User Profile</h4>
            </div>
            <div class="modal-body">
 
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">

                        <hr />
                        @Html.ValidationSummary(true)

                        <div class="form-group">
                            <div class="form-group">
                                @Html.LabelFor(model => model.FrirstName, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.FrirstName)
                                    @Html.ValidationMessageFor(model => model.FrirstName)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.LastName)
                                    @Html.ValidationMessageFor(model => model.LastName)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.MidName, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.MidName)
                                    @Html.ValidationMessageFor(model => model.MidName)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.LoginName, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.LoginName)
                                    @Html.ValidationMessageFor(model => model.LoginName)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Password)
                                    @Html.ValidationMessageFor(model => model.Password)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Email)
                                    @Html.ValidationMessageFor(model => model.Email)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Telephone, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Telephone)
                                    @Html.ValidationMessageFor(model => model.Telephone)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Status, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Status)
                                    @Html.ValidationMessageFor(model => model.Status)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.DateCreate, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.DateCreate)
                                    @Html.ValidationMessageFor(model => model.DateCreate)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.DateUpdate, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.DateUpdate)
                                    @Html.ValidationMessageFor(model => model.DateUpdate)
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Create" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }
                 


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">




            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>-->
 

ICTS.Dashboard/Views/ICTWF/Delete.cshtml
@model ICTS.Data.UserProfile

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserProfile</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FrirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FrirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MidName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MidName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoginName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoginName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telephone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateUpdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateUpdate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ICTS.Dashboard/Views/ICTWF/Details.cshtml
@model ICTS.Data.UserProfile

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>UserProfile</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FrirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FrirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MidName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MidName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoginName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoginName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telephone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateUpdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateUpdate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ICTS.Dashboard/Views/ICTWF/Edit.cshtml
@model ICTS.Data.UserProfile

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserProfile</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FrirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FrirstName)
                @Html.ValidationMessageFor(model => model.FrirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName)
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MidName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MidName)
                @Html.ValidationMessageFor(model => model.MidName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LoginName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LoginName)
                @Html.ValidationMessageFor(model => model.LoginName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telephone, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telephone)
                @Html.ValidationMessageFor(model => model.Telephone)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status)
                @Html.ValidationMessageFor(model => model.Status)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreate)
                @Html.ValidationMessageFor(model => model.DateCreate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateUpdate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateUpdate)
                @Html.ValidationMessageFor(model => model.DateUpdate)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ICTS.Dashboard/Views/ICTWF/Index.cshtml
@model IEnumerable<ICTS.Data.UserProfile>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>


<p>
    @Html.ActionLink("Create User Profile WF", "CreateUserWF", "ICTWF")
</p>


<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FrirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MidName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LoginName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telephone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateCreate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateUpdate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FrirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MidName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LoginName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telephone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateCreate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateUpdate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

ICTS.Dashboard/Views/ICTWF/ValidateTask.cshtml
@{
    ViewBag.Title = "ValidateTask";
    Layout = "~/Views/Shared/_Layout.cshtml";
}